
EJERCICIO 1: Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:
 - El valor de la primera fila y la segunda columna.
 - Los valores de la segunda fila y las dos primeras columnas.
 - Extraed las filas pares (incluyendo la 0) y todas las columnas.
 - Extraed los valores que sean mayores que 0.5.
 - Extraed los valores menores que 0.2 o mayores que 0.5

In [1]:
import numpy as np

In [4]:
np.random.seed(5)
array1 = np.random.randint(0,50,(5,3))
array1

array([[35, 14, 47],
       [38, 16,  9],
       [ 8, 36, 39],
       [27, 48, 30],
       [16,  7, 12]])

In [5]:
# El valor de la primera fila y la segunda columna

array1[0,1]

14

In [6]:
# Los valores de la segunda fila y las dos primeras columnas.

array1[1,:2]

array([38, 16])

In [7]:
# Extraed las filas pares (incluyendo la 0) y todas las columnas.

array1[::2,:]

array([[35, 14, 47],
       [ 8, 36, 39],
       [16,  7, 12]])

In [10]:
# Extraed los valores que sean mayores que 0.5.

array1[(array1>0.5)]

array([35, 14, 47, 38, 16,  9,  8, 36, 39, 27, 48, 30, 16,  7, 12])

In [11]:
# Extraed los valores menores que 0.2 o mayores que 0.5

array1[(array1>0.5)|(array1<0.2)]

array([35, 14, 47, 38, 16,  9,  8, 36, 39, 27, 48, 30, 16,  7, 12])

EJERCICIO 2: Cread dos array de tres dimensiones:
 - El primero de 2 matrices, 5 filas y 3 columnas.
 - El segundo de 3 matrices, 2 filas y 5 columnas
 - Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.
 - Sumad los dos arrays. ¿Podéis? ¿Por qué?
 - Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
    - .reshape()
    - .transpose()
 - Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [13]:
np.random.seed(6)
array2 = np.random.randint(0,50,(2,5,3))
array2

array([[[10,  9, 35],
        [20, 42, 45],
        [15, 42, 16],
        [25,  1, 11],
        [13, 26, 47]],

       [[33, 44, 46],
        [ 4, 33,  8],
        [ 2, 12, 20],
        [27, 31,  2],
        [ 5, 26, 15]]])

In [15]:
np.random.seed(7)
array3 = np.random.randint(0,50,(3,2,5))
array3

array([[[47,  4, 25,  3, 19],
        [23, 39, 28, 14, 23]],

       [[ 8, 25, 46, 42, 26],
        [ 8, 39, 38,  4, 48]],

       [[ 7, 44,  0, 11,  6],
        [19, 44,  5, 24, 48]]])

In [16]:
# Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

def propiedades_array(array):
    lista=[]
    lista.append(array.shape)
    lista.append(array.size)
    lista.append(array.ndim)
    lista.append(array.dtype)
    return lista

In [17]:
propiedades_array(array2)

[(2, 5, 3), 30, 3, dtype('int64')]

In [18]:
propiedades_array(array3)

[(3, 2, 5), 30, 3, dtype('int64')]

In [19]:
# Sumad los dos arrays. ¿Podéis? ¿Por qué?

## No se puede porque tenemos dos matrices con formas distintas
array2 + array3

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

In [20]:
# Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
    # .reshape()
    #.transpose()
#Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

r3 = array3.reshape(2,5,3)

In [21]:
array2 + r3

array([[[57, 13, 60],
        [23, 61, 68],
        [54, 70, 30],
        [48,  9, 36],
        [59, 68, 73]],

       [[41, 83, 84],
        [ 8, 81, 15],
        [46, 12, 31],
        [33, 50, 46],
        [10, 50, 63]]])

In [22]:
t3 = array3.transpose(1,2,0)

In [23]:
array2 + t3

array([[[57, 17, 42],
        [24, 67, 89],
        [40, 88, 16],
        [28, 43, 22],
        [32, 52, 53]],

       [[56, 52, 65],
        [43, 72, 52],
        [30, 50, 25],
        [41, 35, 26],
        [28, 74, 63]]])