EJERCICIO 1
¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores? 

In [3]:
import numpy as np

In [4]:
#CON EL METODO SEED ESTAOS FIJANDO LAS VARIABLES PSEUDO_RANDOM DE FORMA QUE CADA VEZ QUE EJECUTEMOS EL METODO SEED Y LUEGO UN ARRAY NOS VA A DEVOLVER LOS MISMOS VALORES

In [5]:
np.random.seed(42)
array1=np.random.sample((2,4))
array1

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615]])

In [6]:
np.random.seed(42)
array2=np.random.sample((2,4))
array2

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615]])

EJERCICIO 2
Cread los siguientes arrays:

 - Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

 - Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes guarda los datos en una variable. 

In [7]:
#Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

array3=np.round(np.random.uniform(0,10,size=(2,3,5)),0)
array3

array([[[ 6.,  7.,  0., 10.,  8.],
        [ 2.,  2.,  2.,  3.,  5.],
        [ 4.,  3.,  6.,  1.,  3.]],

       [[ 4.,  5.,  8.,  2.,  5.],
        [ 6.,  0.,  6.,  2.,  1.],
        [ 9., 10.,  8.,  3.,  1.]]])

In [8]:
unico=np.unique(array3)
unico

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
#Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes guarda los datos en una variable. 
array4=np.random.binomial(10,0.3,size=(2,3,5))
array4

array([[[4, 3, 1, 3, 1],
        [5, 2, 4, 2, 3],
        [3, 2, 6, 4, 5]],

       [[5, 3, 5, 1, 2],
        [1, 2, 3, 2, 4],
        [2, 2, 3, 1, 4]]])

In [10]:
unico2=np.unique(array4)
unico2

array([1, 2, 3, 4, 5, 6])

EJERCICIO 3
En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:

 - Elementos comunes entre los dos arrays

 - Unión de los dos arrays

 - ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

⚠️  - Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo? 

In [11]:
#Elementos comunes entre los dos arrays

comun=np.intersect1d(unico, unico2)
comun

##NOS DEVUELVE TODOS LOS ELEMENTOS COMUNES EN LAS DOS ARRAYS

array([1., 2., 3., 4., 5., 6.])

In [12]:
# Unión de los dos arrays

union=np.union1d(unico,unico2)
union

##NOS DEVUELVE DE FORMA UNICA LOS VALORES CONTENIDOS EN AMBOS ARRAYS

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
#¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

diferencia=np.setdiff1d(array1,unico2)
diferencia

##NOS DEUELVE AQUELLOS ELEMENTOS QUE ESTAN ENE EL ARRAY1 PERO NO EN UNICO2

array([0.05808361, 0.15599452, 0.15601864, 0.37454012, 0.59865848,
       0.73199394, 0.86617615, 0.95071431])

EJERCICIO 4

Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

 - Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

 - Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

 - Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

 - Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

 - ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados. 

In [14]:
#Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

np.random.seed(2)

arr1 = np.random.randint(1,100,(80))

arr2 = np.random.randint(1,100,(80))

In [15]:
arr1

array([41, 16, 73, 23, 44, 83, 76,  8, 35, 50, 96, 76, 86, 48, 64, 32, 91,
       21, 38, 40, 68,  5, 43, 52, 39, 34, 59, 68, 70, 89, 69, 47, 71, 96,
       84, 32, 67, 81, 53, 77, 51,  5, 91, 64, 80, 50, 40, 47,  9, 51, 16,
        9, 18, 23, 74, 58, 91, 63, 84, 97, 44, 33, 27,  9, 77, 11, 41, 35,
       61, 10, 71, 87, 71, 20, 57, 83,  2, 69, 41, 82])

In [16]:
arr2

array([62, 71, 98, 19, 85, 91, 88, 23, 44, 53, 75, 73, 91, 92, 97, 17, 56,
       22, 44, 94, 81, 41, 71, 75, 38, 60, 18, 16, 31, 78, 27, 40, 64, 21,
       23, 60, 50, 28,  1, 63, 41, 59, 93, 37, 64, 76, 51, 74,  8, 50, 83,
        2, 80, 92, 97, 50, 41, 47, 60, 74, 79, 95, 96, 33, 17, 22, 44, 59,
       99, 22, 50, 64, 84, 93, 52, 98,  9, 87, 89, 12])

In [17]:
#Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

arr1,arr2 = np.unique(arr1), np.unique(arr2)

arr1,arr2

(array([ 2,  5,  8,  9, 10, 11, 16, 18, 20, 21, 23, 27, 32, 33, 34, 35, 38,
        39, 40, 41, 43, 44, 47, 48, 50, 51, 52, 53, 57, 58, 59, 61, 63, 64,
        67, 68, 69, 70, 71, 73, 74, 76, 77, 80, 81, 82, 83, 84, 86, 87, 89,
        91, 96, 97]),
 array([ 1,  2,  8,  9, 12, 16, 17, 18, 19, 21, 22, 23, 27, 28, 31, 33, 37,
        38, 40, 41, 44, 47, 50, 51, 52, 53, 56, 59, 60, 62, 63, 64, 71, 73,
        74, 75, 76, 78, 79, 80, 81, 83, 84, 85, 87, 88, 89, 91, 92, 93, 94,
        95, 96, 97, 98, 99]))

In [18]:
#Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

arr3 = np.setdiff1d(arr1,arr2)
arr3

array([ 5, 10, 11, 20, 32, 34, 35, 39, 43, 48, 57, 58, 61, 67, 68, 69, 70,
       77, 82, 86])

In [19]:
#Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4

arr4 = np.setdiff1d(arr2,arr1)
arr4

array([ 1, 12, 17, 19, 22, 28, 31, 37, 56, 60, 62, 75, 78, 79, 85, 88, 92,
       93, 94, 95, 98, 99])

In [20]:
#Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

arr5 = np.setxor1d(arr1,arr2)
arr5

array([ 1,  5, 10, 11, 12, 17, 19, 20, 22, 28, 31, 32, 34, 35, 37, 39, 43,
       48, 56, 57, 58, 60, 61, 62, 67, 68, 69, 70, 75, 77, 78, 79, 82, 85,
       86, 88, 92, 93, 94, 95, 98, 99])

In [21]:
#¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

## COMO ARR3 REPRESENTA LOS VALORES UNICOS EN ARR1 QUE NO ESTAN EN ARR2 Y ARR4 REPRESENTA LO MISMO PERO DE ARR2 EN ARR1 CUANDO CALCULAMOS ARR5 SU LONGITUD ES IGUAL 
# A LA SUMA DE LA LONGITUD DE ARR3 Y ARR4, NOS ESTA DANDO LOS VALORES UNICOS PRESENTES EN LOS DOS ARRAYS.

In [22]:
arr1.size

54

In [23]:
arr2.size

56

In [24]:
arr3.size

20

In [25]:
arr4.size

22

In [26]:
arr5.size

42