EJERCICIO 1 Cread tres arrays: de una, dos y tres dimensiones.
    Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.
 - El array de 2 dimensiones debe ser de 2 filas y 3 columnas
 - El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas


In [1]:
import numpy as np

In [2]:
array1=np.random.randint(0,10,(5))
array1

array([9, 7, 6, 2, 8])

In [5]:
array2=np.random.rand(2,3)
array2

array([[0.01627589, 0.24699496, 0.96741657],
       [0.18747775, 0.26051926, 0.62704805]])

In [7]:
array3=np.random.sample((2,3,5))
array3

array([[[0.28022609, 0.79305264, 0.07496486, 0.05458802, 0.98297445],
        [0.89951515, 0.80282436, 0.86550364, 0.4797823 , 0.26212415],
        [0.98867723, 0.40559556, 0.33484086, 0.77169153, 0.91884399]],

       [[0.83637667, 0.68228522, 0.5511076 , 0.71526808, 0.89687347],
        [0.50497829, 0.21651293, 0.83345213, 0.14483924, 0.38489914],
        [0.63528216, 0.66578129, 0.09123056, 0.31449045, 0.11968824]]])

EJERCICIO 2 Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos. 

In [8]:
def propiedades_array(array):
    lista=[]
    lista.append(array.shape)
    lista.append(array.size)
    lista.append(array.ndim)
    lista.append(array.dtype)
    return lista

In [21]:
primera=propiedades_array(array1)
primera

[(5,), 5, 1, dtype('int64')]

In [22]:
segunda=propiedades_array(array2)
segunda

[(2, 3), 6, 2, dtype('float64')]

In [23]:
tercera=propiedades_array(array3)
tercera

[(2, 3, 5), 30, 3, dtype('float64')]

EJERCICIO 3
Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas 

In [27]:
array4=np.identity(3)
array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

EJERCICIO 4 
Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio. 

In [28]:
array5=np.ones_like(array3)
array5

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

EJERCICIO 5 Es el momento de hacer algunas operaciones entre arrays
 - ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?
 - En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.
 - Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.
 - Dividid las dos matricess 

In [29]:
#¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?
print(array2)
print(array4)

[[0.01627589 0.24699496 0.96741657]
 [0.18747775 0.26051926 0.62704805]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
## para sumar dos matrices, tienen que tener la misma forma. Comprobamos la forma de las dos matrices:
print(array2.shape)
print(array4.shape)

(2, 3)
(3, 3)


In [31]:
## No se pueden sumar porque tienen distinta forma

In [33]:
#En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.
array4
array6=np.ones_like(array4)
array7=array4+array6
array7

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [35]:
#Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.
array8=array4*array7
array8

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [36]:
#Dividid las dos matrices 
array9=array4/array7
array9

array([[0.5, 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 0.5]])

In [38]:
array7

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [37]:
array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])