EJERCICIO 1
Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. 
Sobre el array creado anteriormente, extraed: 

In [2]:
import numpy as np

In [3]:
np.random.seed(5)
array1 = np.random.rand(2,3,5)
array1 

array([[[0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119],
        [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123],
        [0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703]],

       [[0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781],
        [0.5999292 , 0.26581912, 0.28468588, 0.25358821, 0.32756395],
        [0.1441643 , 0.16561286, 0.96393053, 0.96022672, 0.18841466]]])

In [10]:
array1=np.round(array1,1)
array1

array([[[0.2, 0.9, 0.2, 0.9, 0.5],
        [0.6, 0.8, 0.5, 0.3, 0.2],
        [0.1, 0.7, 0.4, 0.2, 0.9]],

       [[0.3, 0.4, 0.3, 0.6, 0.6],
        [0.6, 0.3, 0.3, 0.3, 0.3],
        [0.1, 0.2, 1. , 1. , 0.2]]])

EJERCICIO 2 Calculad la media del array y almacenarlos en una variable. Redondead a un decimal. 

In [5]:
media=round(np.mean(array1),1)
media

0.5

EJERCICIO 3 Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal. 

In [6]:
maximo=round(np.max(array1),1)
maximo

1.0

EJERCICIO 4
Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal. 

In [7]:
minimo=round(np.min(array1),1)
minimo

0.1

EJERCICIO 5

Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
Si el valor del array es igual que la media, se reemplaza por "A".
Si el valor del array es mayor que la media, se reemplaza por "B".
Si el valor del array es menor que la media, se reemplaza por "C".
Si el valor es igual que el máximo, se reemplaza por "D".
Si el valor es igual que el mínimo, se reemplaza por "E". 


In [19]:
array_v=np.empty_like(array1,str)
array_v

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [22]:
array_v.shape

(2, 3, 5)

In [49]:
for x in range(0,2):
    for y in range(0,3):
        for z in range(0,5):
                        
            if array1[x][y][z]== maximo:
                array_v[x][y][z]="D"
                
            elif array1[x][y][z]== minimo:
                array_v[x][y][z]="E"
            elif array1[x][y][z] == media:
                array_v[x][y][z]="A"
                
            elif array1[x][y][z]> media:
                array_v[x][y][z]="B"
                
            elif array1[x][y][z]< media:
                array_v[x][y][z]="C"
                
            elif array1[x][y][z]== maximo:
                array_v[x][y][z]="D"
                
            elif array1[x][y][z]== minimo:
                array_v[x][y][z]="E"
                
print(array_v)

[[['C' 'B' 'C' 'B' 'A']
  ['B' 'B' 'A' 'C' 'C']
  ['E' 'B' 'C' 'C' 'B']]

 [['C' 'C' 'C' 'B' 'B']
  ['B' 'C' 'C' 'C' 'C']
  ['E' 'C' 'D' 'D' 'C']]]


6.Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.
En este caso:
 - Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
 - Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
 - Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.
 - Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [50]:
array_z = np.reshape(array_v,(30))
array_z

array(['C', 'B', 'C', 'B', 'A', 'B', 'B', 'A', 'C', 'C', 'E', 'B', 'C',
       'C', 'B', 'C', 'C', 'C', 'B', 'B', 'B', 'C', 'C', 'C', 'C', 'E',
       'C', 'D', 'D', 'C'], dtype='<U1')

In [57]:
array_vacia = np.empty(30)
array_vacia

array([4.9e-324, 1.5e-323, 1.5e-323, 9.9e-324, 4.9e-324, 4.9e-324,
       1.5e-323, 0.0e+000, 0.0e+000, 4.9e-324, 9.9e-324, 9.9e-324,
       1.5e-323, 1.5e-323, 1.5e-323, 0.0e+000, 4.9e-324, 1.5e-323,
       1.5e-323, 1.5e-323, 9.9e-324, 1.5e-323, 4.9e-324, 4.9e-324,
       4.9e-324, 4.9e-324, 1.5e-323, 0.0e+000, 9.9e-324, 9.9e-324])

In [39]:
array_z.shape

(30,)

In [58]:
for z in range(0,30):
    if array_z[z] == 'A' or 'B':
        array_vacia[z] = 1
    elif array_z[z] == 'C' or 'D':
        array_vacia[z] = 2
    elif array_z[z] == 'E':
        array_vacia[z] = 3
array_vacia


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])